### PR TITLE
add evaluation code and ncnn module

### PR DESCRIPTION
**Pull request by vealocia**
this is the new version of ncnn c++ code. fixed bugs in #33

### CODE REVIEW

**Comment by Linzaer** [comment]
Nice work, you work fast. I coded half of it yesterday. I'll check it soon.

**Comment by ingjieye** [comment]
I've tested your code and everything works great, nice work.

I'll patch some including issues along side with adding the `CMakeLists.txt` once the PR have been accepted. 

Also that you code doesn't support 640 `input_size` as the original author provided. 

The 320 `input_size` model doesn't works great on the flowing image (both yours and the original python version). while the 640 `input_size` works great. 

So it'll be so nice if you adding the 640 `input_size` support. 

original:


320 `input_size`


640 `input_size`

**Comment by Linzaer** [comment]
I'll add other input_size supports and modify some code soon.

**Comment by vealocia** [comment]
thanks for all your works and suggestions.

**Comment by Linzaer** [comment]
And I found the boxes in the uploaded result img have some  deviations.(run on android?). I will upload the result img which has the same boxes with the python version.

**Comment by Linzaer** [comment]
@ingjieye You can test it again. Thank you again for your contribution and testing!@vealocia @ingjieye

**Comment by vealocia** [comment]
> And I found the boxes in the uploaded result img have some deviations.(run on android?). I will upload the result img which has the same boxes with the python version.

uploaded image in my code was generated by 128-input-size model. so this deviations occurred.

**Comment by Linzaer** [comment]
@vealocia Got it !Thank you for your contribution.

**Pull request merged**
