### PR TITLE
Translated README.md into english

### LINKED ISSUE #27: Can someone translate this repo to English?

### PR DESCRIPTION
**Pull request by TheMisir**
Translated using Google Translate, fixes https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/issues/27

### CODE REVIEW

**Comment by Linzaer** [comment]
Hi,@TheMisir.Thank u for your contribution.I'll check it as soon as I have time.

**Comment by upura** [comment]
Some markdown for unordered list doesn't work because of unnecessary space. (See [preview](https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/9eb06545f9acc903f98431678c66be6ba0ea7e45/README_EN.md))

**Comment by TheMisir** [comment]
Ok, I will fix it

--
Misir Jafarov

**Comment by TheMisir** [comment]
I fixed and will open new PR.

**Pull request closed without merging**
